// Ignore Spelling: Sha

using iExcelNetwork.NetworkProperty;
using System.IO;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;

namespace iExcelNetwork.VisJsNetwork
{
    public class NetworkIntegrityLog
    {
        private readonly NetworkProperties _networkProperties;

        public NetworkIntegrityLog(NetworkProperties networkProperties)
        {
            _networkProperties = networkProperties;
        }

        public void WriteLog()
        {
            string networkHtmlFileSha256 = ComputeSha256HashFromFile(_networkProperties.OutputFolder, _networkProperties.OutputFileName);
            
            string networkHtmlFilePath = BuildFullFilePath(_networkProperties.OutputFolder,_networkProperties.OutputFileName);

            string logFilePath = SubstituteFileExtention(networkHtmlFilePath, ".txt");

            string[] lodFileContent = LogFileContent(GetAssamblyInformationalVersion(), _networkProperties.OutputFileName, networkHtmlFileSha256);

            File.WriteAllLines(logFilePath, lodFileContent);
        }

        private string[] LogFileContent(string iExcelNetworkVersion, string networkFileName, string fileSha256checksum)
        {
            string[] content = {
                $"Network was generated by Excel Add-in iExcelNetwork ver: {iExcelNetworkVersion}.",
                "",
                $"Generated file's name: {networkFileName}.html",
                $"SHA256: {fileSha256checksum}",
                "",
                "iExcelNetwork is open source project under MIT license.",
                "Project source code is available: https://github.com/Alek010/iExcelNetwork"
            };

            return content;
        }

        private string ComputeSha256HashFromFile(string pathToFolder, string fileName)
        {
            byte[] fileBytes = File.ReadAllBytes(BuildFullFilePath(pathToFolder, fileName));

            using (SHA256 sha256Hash = SHA256.Create())
            {
                byte[] bytes = sha256Hash.ComputeHash(fileBytes);

                StringBuilder builder = new StringBuilder();
                for (int i = 0; i < bytes.Length; i++)
                {
                    builder.Append(bytes[i].ToString("x2"));
                }
                return builder.ToString();
            }
        }

        private string SubstituteFileExtention(string filePath, string fileExtention)
        {
            return Path.ChangeExtension(filePath, fileExtention);
        }

        private string BuildFullFilePath(string folderPath, string fileName)
        {
            return Path.Combine(folderPath, fileName) + ".html";
        }

        private string GetAssamblyInformationalVersion()
        {
            Assembly assembly = Assembly.GetExecutingAssembly();

            var informationalVersionAttribute = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();

            return informationalVersionAttribute?.InformationalVersion ?? "N/A";
        }
    }
}
